### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by techseria** [openboxes/openboxes#1114]
We are getting access denied message for 2 menus though we are login as the admin user.
1. Add Transmission
2. Console

**Comment by jmiranda** [comment]
You need to be a Superuser to access those menu items. We added the Superuser role because we needed to prevent access to sensitive features like these and to have a single role with the ability to delete database records. 

There's a bug (although more of an intentional loophole) in the security code that allows a user with the Admin role to update their own user roles (as well as the user roles of others). Therefore, the admin user can upgrade their default user role to Superuser. I'm going to close this loophole in a future release, but I'll have a database migration to convert the admin user to Superuser before I make that change. The reason I didn't patch this earlier is because system administrators would need to make the user role change directly to the database, which I thought was less than appealing.

**Comment by techseria** [comment]
We have fixed this issue.
