### ISSUE TITLE
Compatablity on iPads

### ISSUE THREAD

**Issue by vegapaul** [openboxes/openboxes#210]
On an iPad when clicking a tab auto goes to the default page. Any way to be able get to sub pages?

**Comment by jmiranda** [comment]
Good question. I haven't promoted OpenBoxes for use on mobile because I know the user experience would be sh*t. The UI hasn't seen a major update since about 2011 (right around the time that mobile / responsive frameworks started popping up). I am planning to move to Bootstrap/Foundation/whatever in an upcoming release but that's not going to happen any time soon. There must be an obvious way to get those menus working on mobile without a huge upgrade. I should be able to test something quickly and maybe get it into the next release going out this week (0.7.22).

**Comment by vegapaul** [comment]
Thank you for quick response. I will be looking forward to hearing further updates.

**Comment by vegapaul** [comment]
Just a thought on the iPad if there is not a default page set. The drop down menu does work. What if the default page was removed. Example "Configuration" the drop down menu does appear, but as with the ":Shipping" has a default page and auto directs to the default page.

**Comment by jmiranda** [comment]
Yes, that's exactly what I was hoping to find. There's no reason for a default linke (besides maybe slight convenience) since the dropdown menu contains same link. Therefore, there's no real good reason to keep it.

**Comment by jmiranda** [comment]
Secondly, I meant to ask how you were planning to use OB on mobile? What features / workflows would you use on iOS?

While a full-on migration to a new UI framework would take some time it would be pretty straightforward to migrate a few features on a case-by-case basis. Let me know what features would be useful on mobile (even new features) and I can start prototyping. This might actually be a good way to test a few JS/UI frameworks since I'm not sold on any of them yet.

**Comment by jmiranda** [comment]
Ok, I just fixed the megamenu and deployed the current release candidate to the demo server so you could test it out.

**Comment by vegapaul** [comment]
We have tested on the demo! The drop down menu is now populating on the iPad! Nice!

**Comment by jmiranda** [comment]
Thanks for the suggestion!

**Comment by vegapaul** [comment]
To answer your question: We are planning to use this to handle logistics for delivery of merchandise to vendors at street fairs. We are still in testing phases not fully sure of features at this moment.

**Comment by vegapaul** [comment]
Sorry, to ask this: What is the best way to deploy this version to my server?

**Comment by jmiranda** [comment]
That's a difficult question to answer without knowing more about your requirements, but take a look at the docs and video for installing OpenBoxes on a cloud provider using Ubuntu 14.04.  

http://docs.openboxes.com/en/latest/installation/ubuntu/

If that doesn't clarify things for you (i.e. you aren't a web developer or sysadmin), send an email to support@openboxes.com so we can discuss your requirements in a private setting and figure out the best way to get the software installed for you.

If you just need a clean demo server to do some proper evaluation you can use our other demo server. However, I haven't installed the latest version there yet, so let me know if that's what you want and I'll deploy the latest version.

https://demo2.openboxes.com/openboxes

**Comment by vegapaul** [comment]
Where do I find the download for 0.7.22?

**Comment by jmiranda** [comment]
Until I get an official release out later this week, you can download the release candidate from our CI server.
http://bamboo.pih-emr.org:8085/browse/OPENBOXES-CORE9-16/artifact/DJ/Latest-WAR/openboxes.war

**Comment by vegapaul** [comment]
Great! I want to say thank you for all your work and quick response. You have been great.

**Comment by vegapaul** [comment]
I have it deployed on our server and testing now.

**Comment by jmiranda** [comment]
Awesome. Let me know if you have any other questions. If you're interested I'd be happy to schedule a demo this week to run through all of the features.

**Comment by vegapaul** [comment]
Is it possible to view a demo and discuss the features on Tue evening?

**Comment by vegapaul** [comment]
How do you handle demos? Telephone? Web? Time 7:15PM?

**Comment by jmiranda** [comment]
Usually via google hangouts. What timezone are you in?

**Comment by vegapaul** [comment]
We are on the East Coast, near DC.

**Comment by jmiranda** [comment]
Ok, that works for me. Send me an email to support@openboxes.com and I'll send you a calendar invite with the google hangout link.
