### ISSUE TITLE
Cannot apply global styles

### ISSUE THREAD

**Issue by Omar-ALkhateeb** [openboxes/openboxes#2208]
I've tried to change main.scss with different styles but not all pages were affected, maybe this is because (based on my understanding) not all pages are react generated and only use jquery UI

so how cant I apply global styles?
sorry for the rookie question.

**Comment by jmiranda** [comment]
Hey @Omar-ALkhateeb. Sorry for the delay in responding.  

> I've tried to change main.scss with different styles but not all pages were affected, maybe this is because (based on my understanding) not all pages are react generated and only use jquery UI

Yes, I think that's probably the correct assumption. We only recently started adding new features in React, so not all pages are using the same style sheet. Most of the existing pages are rendered using a server-side technology called Groovy Server Pages (GSP). The main CSS for those pages is openboxes.css. Unlike main.scss it is a static resource and is only used by the legacy UI. We have plans to migrate those features to Bootstrap (and eventually React), at which point we'd probably switch over to using main.scss for all pages.

> so how cant I apply global styles?

I think this depends on what you're trying to do. We could potentially add a configurable external CSS URL that would allow you to customize the CSS for both GSP and React pages. But I'd really like to know what changes you want to make before I send you down that path.

> sorry for the rookie question.

Not a rookie question at all. It's been awhile since I've thought about the work that needs to go into refactoring our UI so this is a good reminder that we still need to do a lot of work on that end. In the interim, hopefully we can come up with a solution that works for you in the short-term.

**Comment by Omar-ALkhateeb** [comment]
Hello @jmiranda thanks for the detailed response, if you want my opinion well I think that the best solution would be moving all pages to react and depend on main.scss (even though some pages are kinda static and simple ) I think this will help moving forward as any changes would be applied through the whole ui.

As for the short term solution I think I'll just use openboxes.css to apply styles to these pages.

**Comment by jmiranda** [comment]
> I think that the best solution would be moving all pages to react and depend on main.scss
Agreed. And that is the ulitmate plan. We just have a lot of pages and not enough time :)

> As for the short term solution I think I'll just use openboxes.css to apply styles to these pages
Could you explain what you're trying to do (i.e. what styles are you chaning)? Changing openboxes.css and/or main.scss might not be the right approach because you'd need to fork the project. Instead I'd like to figure out a way to make it configurable to add an external CSS file.

**Comment by Omar-ALkhateeb** [comment]
Well I'm trying to implement this project here in Iraq so fully translate these pages to Arabic, make the font bigger and some color and size changes in the ui (navbar, footer, etc)

**Comment by jmiranda** [comment]
Does that also involve RTL support? 

Let me know what you come up with for any/all of these changes and I'll do my best to include them in core or figure out a way to include them as external config so you don't have to manage your own fork.

**Comment by jmiranda** [comment]
Hey @Omar-ALkhateeb. We're getting ready to start QA on the 0.8.15 release. Let me know if there's anything specific I can do to help with this ticket.
