### ISSUE TITLE
Error while installing openboxes with grails 3

### ISSUE THREAD

**Issue by nivl98** [openboxes/openboxes#4706]
I'm facing an issue trying to run openboxes with grails 3, Java 8. 

set at /etc/systemd/system/openboxes.service: 
ExecStart=/home/ubuntu/.sdkman/candidates/java/current/bin/java -Dgrails.env=prod -jar /opt/openboxes/openboxes.war

got the openboxes.war file from: https://github.com/openboxes/openboxes/releases/tag/v0.8.23-hotfix1 located at /opt/openboxes/openboxes.war

run:
sudo systemctl daemon-reload
sudo systemctl restart openboxes

then get error log: 
no main manifest attribute, in /opt/openboxes/openboxes.war
openboxes.service: Main process exited, code=exited, status=1/FAILURE
openboxes.service: Failed with result 'exit-code'.

Any suggestions please?

**Comment by jmiranda** [comment]
@nivl98 You'll need to use a 0.9.x version of OpenBoxes to get it running with Grails 3 / Java 8. We are currently working on migration documentation for 0.9.2 which is the version we're hoping to officially release to the community. 

But since you're probably eager to get it working, you can download a snapshot build of 0.9.2 from our CI/CD server. 
https://bamboo-ci.pih-emr.org/browse/OPENBOXES-OBDEV3/latest/artifact

Let me know if you encounter any other issues.

**Comment by nivl98** [comment]
Yeah ok now it's running
You have to update your installation docs, its a nightmare  
Thanks a lot

**Comment by jmiranda** [comment]
Thanks @nivl98. We are aware :)
